github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Mojarra]
description: [Eclipse EE4J implementation of Jakarta Faces]

links:
  source: https://github.com/eclipse-ee4j/mojarra
  javadocs: https://javadoc.io/doc/jakarta.faces/jakarta.faces-api
  issues_url: site.github.issues_url
  download: https://github.com/eclipse-ee4j/mojarra/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/mojarra-dev
  # faq: FAQ

include:
  - LICENSE.md
  - CONTRIBUTING.md